version: '3'
services:
        broker:
                image: spotify/kafka
        
        producer:
                build:
                        context: ./producer
                        dockerfile: Dockerfile
                image: tumble-kafka:producer
              
        consumer:
                build:
                        context: ./consumer
                        dockerfile: Dockerfile
                image: tumble-kafka:consumer
