version: '3'
services:
        producer:
                build:
                        context: ./producer
                        dockerfile: Dockerfile-producer
                image:
                        kafka-producer:jd
        
        broker:
                build:
                        context: ./broker
                        dockerfile: Dockerfile-broker
                image:
                        kafka-broker:jd

        consumer:
                build:
                        context: ./consumer
                        dockerfile: Dockerfile-consumer
                image:
                        kafka-consumer:jd
