version: '3'
services:
        kafka:
                build:
                        context: ./
                        dockerfile: Dockerfile
                image: tumble-kafka:broker
                ports:
                 - "2181:2181"
                 - "9092:9092"
